# Generated by Django 5.0 on 2024-08-20 19:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 19, 13, 28, 460928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='project', verbose_name='Video')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Project Videos',
            },
        ),
    ]
