# Generated by Django 5.0 on 2024-08-21 18:09

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='path',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=project.models.photo_upload_to),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=project.models.video_upload_to),
        ),
    ]
